-- views for viewing data and testing tables

CREATE OR REPLACE VIEW COUNTRY_VIEW AS
SELECT *
FROM COUNTRY;
SELECT * FROM COUNTRY_VIEW;

CREATE OR REPLACE VIEW OLYMPIAD_VIEW AS
SELECT *
FROM OLYMPIAD;
SELECT * FROM OLYMPIAD_VIEW;

CREATE OR REPLACE VIEW SPORT_VIEW AS
SELECT *
FROM SPORT;
SELECT * FROM SPORT_VIEW;

CREATE OR REPLACE VIEW ACCOUNT_VIEW AS
SELECT *
FROM ACCOUNT;
SELECT * FROM ACCOUNT_VIEW;

SELECT removeAccount(1);
CREATE OR REPLACE VIEW DELETED_ACCOUNT_VIEW AS
SELECT *
FROM ACCOUNT;
SELECT * FROM DELETED_ACCOUNT_VIEW;


CREATE OR REPLACE VIEW PARTICIPANT_VIEW AS
SELECT *
FROM PARTICIPANT;
SELECT * FROM PARTICIPANT_VIEW;

SELECT removeParticipant(5);
CREATE OR REPLACE VIEW DELETED_PARTICIPANT_VIEW AS
SELECT *
FROM PARTICIPANT;
SELECT * FROM DELETED_PARTICIPANT_VIEW;

CREATE OR REPLACE VIEW TEAM_VIEW AS
SELECT *
FROM TEAM;
SELECT * FROM TEAM_VIEW;

CREATE OR REPLACE VIEW TEAM_MEMBERS_VIEW AS
SELECT *
FROM TEAM_MEMBERS;
SELECT * FROM TEAM_MEMBERS_VIEW;

SELECT addTeamMember(8, 1);
CREATE OR REPLACE VIEW ADD_TEAM_MEMBERS_VIEW AS
SELECT *
FROM TEAM_MEMBERS;
SELECT * FROM ADD_TEAM_MEMBERS_VIEW;

SELECT removeTeamMember(33,14);
CREATE OR REPLACE VIEW REMOVE_TEAM_MEMBERS_VIEW AS
SELECT *
FROM TEAM_MEMBERS;
SELECT * FROM REMOVE_TEAM_MEMBERS_VIEW;


CREATE OR REPLACE VIEW VENUE_VIEW AS
SELECT *
FROM VENUE;
SELECT * FROM VENUE_VIEW;

CREATE OR REPLACE VIEW EVENT_VIEW AS
SELECT *
FROM EVENT;
SELECT * FROM EVENT_VIEW;

CREATE OR REPLACE VIEW MEDAL_VIEW AS
SELECT *
FROM MEDAL;
SELECT * FROM MEDAL_VIEW;

CREATE OR REPLACE VIEW PLACEMENT_VIEW AS
SELECT *
FROM PLACEMENT;
SELECT * FROM PLACEMENT_VIEW;

--SELECT addTeamToEvent(1,6);
--CREATE OR REPLACE VIEW ADDED_PLACEMENT_VIEW AS
--SELECT *
--FROM PLACEMENT;
--SELECT * FROM ADDED_PLACEMENT_VIEW;

--SELECT addEventOutcome(1,5,2);
--CREATE OR REPLACE VIEW ADDED_EVENT_OUTCOME_VIEW AS
--SELECT *
--FROM PLACEMENT;
--SELECT * FROM ADDED_EVENT_OUTCOME_VIEW;

SELECT disqualifyTeam(1);
CREATE OR REPLACE VIEW DISQUALIFIED_VIEW AS
SELECT *
FROM PLACEMENT;
SELECT * FROM DISQUALIFIED_VIEW;

SELECT * FROM listVenuesInOlympiad('XXIV');
SELECT * FROM listEventsOfOlympiad('XXXII');
SELECT * FROM listTeamsInEvent(1);
SELECT * FROM showPlacementsInEvent(1);
SELECT * FROM listParticipantsOnTeam(6);
SELECT * FROM listcountryplacementsinolympiad('CHN','XXXII');
SELECT * FROM listathleteplacement(8);

SELECT * FROM countryRankings();
SELECT * FROM topSports(3, 3);

